version: '3.4'

services:
    db:
      image: livraria-sqlserver
      build:
        context: .
        dockerfile: ./DB/Dockerfile
      ports:
        - "1433:1433"

    backend:
      image: livraria-backend
      restart: always
      build: ./Livraria-API/
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker
      ports:
        - "8000:80"
      depends_on:
        - db    
